server:
  port: 9001
spring:
  application:
    name: fms-ai-client

  ai:
    mcp:
      client:
        type: sync
        sse:
          connections:
            stock-server:
              sse-endpoint: /sse
              url: http://localhost:9000
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
    openai:
      api-key:

